[versions]
coroutines_version = "1.8.1"
dex2jar_version = "2.4.21"
kotlin_version = "2.0.0"
okhttp_version = "5.0.0-alpha.14"
serialization_version = "1.7.1"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines_version" }
coroutines-jdk = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines_version" }

injekt-core = { module = "com.github.mihonapp:injekt", version = "91edab2317" }
jsoup = "org.jsoup:jsoup:1.18.1"
rxjava = "io.reactivex:rxjava:1.3.8"

kodein-di = "org.kodein.di:kodein-di-conf-jvm:7.22.0"

gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }

# OkHttp
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp_version" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp_version" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp_version" }
okio = "com.squareup.okio:okio:3.9.0"

# Serialization
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization_version" }
serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization_version" }
serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization_version" }

# Logging
sfl4j-api = "org.slf4j:slf4j-api:2.0.13"
logback = "ch.qos.logback:logback-classic:1.5.6"
ktlogging = "io.github.oshai:kotlin-logging-jvm:7.0.0"

d2j-translator = { module = "de.femtopedia.dex2jar:dex-translator", version.ref = "dex2jar_version" }
d2j-tools = { module = "de.femtopedia.dex2jar:dex-tools", version.ref = "dex2jar_version" }

apkparser = "net.dongliu:apk-parser:2.6.10"

[bundles]
coroutines = ["coroutines-core", "coroutines-jdk"]
dex2jar = ["d2j-translator", "d2j-tools"]
extensions_deps = ["jsoup", "injekt-core", "rxjava"]
logging = ["ktlogging", "logback", "sfl4j-api"]
okhttp = ["okhttp-core", "okhttp-dnsoverhttps", "okhttp-logging", "okio"]
serialization = [
    "serialization-json",
    "serialization-json-okio",
    "serialization-protobuf",
]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.5.4" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.16.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
